channels:
  - conda-forge
  #- pytorch
  #- nvidia
  - nodefaults
channel_priority: strict
dependencies:
  #- python(">=3.11.0,<3.14.0")
  - esmpy
  - xesmf
  #- poetry

# - python=3.12.11
  #- pytorch>=2.6.0,<3.0.0
  # - pytorch>=2.6.0  # PyTorch s'occupe de CUDA automatiquement
  # - cudatoolkit=12.6  # Spécifie la version de CUDA
   
#  - python>=3.11,<3.13
  # - netcdf4>=1.6.4,<=1.6.5
  # - pyinterp>=2025.3.0
  # - boost-cpp>=1.79
  # - eigen>=3.3.1
  # - openblas
  # - lapack
  # - blas
  # - cmake
  # - pkg-config