[tool.poetry]
name = "dctools"
version = "0.0.1"
description = "Basic tools common to all data challenges."
authors = ["Kamel Ait Mohand, Guillermo Cossio"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jejjohnson/ocn-tools"
keywords = ["xarray", "sea-surface-height", "ocean", "benchmark"]
classifiers = [
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries",
    "Programming Language :: Python :: 3.13",
    "Operating System :: MACOS/Linux",
    "Natural Language :: English",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Science/Research",
    "Development Status :: 2 - Pre-Alpha copy",
]

[tool.poetry.dependencies]
python = "3.13.*"
pyinterp = "*"
xarray = "*"
zarr = "*"
dask = "*"
netcdf4 = "*"
bottleneck = "*"
scipy = "*"
cmake = "*"
numpy-groupies = "*"
pint-xarray = "*"
xrft = "*"
metpy = "*"
rootutils = "*"
numpy = "*"
tox = "*"
pydocstyle = "*"
wget = "*"
argopy = "*"
xesmf = "*"
copernicusmarine = "*"
oceanbench = { git = "https://aitmohandk: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@github.com:mercator-ocean/oceanbench.git", branch = "main" }

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
pre-commit = "*"
beartype = "*"
ruff = "*"
black = "*"
isort = "*"


[tool.poetry.group.exp.dependencies]
wandb = "*"
loguru = "*"
hydra-core = "*"
matplotlib = "*"
seaborn = "*"
autoroot = "*"
omegaconf = "*"

[tool.poetry.group.jlab.dependencies]
ipykernel = "*"
autoroot = "*"


[tool.poetry.group.jbook.dependencies]
jupyter-book = "*"
ghp-import  = "*"
sphinx-proof = "*"
jupytext = "*"


[build-system]
requires = ["poetry-core", "cmake"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["dctools"]


[tool.ruff]
lint.select = []
lint.ignore = []
lint.ignore-init-module-imports = true

[tool.ruff.lint.isort]
combine-as-imports = true
lines-after-imports = 2
extra-standard-library = ["typing_extensions"]
order-by-type = false
