[project]
name = "dctools"
description = "Basic tools common to all data challenges."
readme = "README.md"
authors = [
    {name="Kamel Ait Mohand"},
    {name="Guillermo Cossio"},
    ]
license = "GPL-3-only"
keywords = ["xarray", "sea-surface-height", "ocean", "benchmark"]
dynamic = [
    "version",
    "classifiers",
    ]
# Too restrictive due to oceanbench
requires-python = ">=3.13.0,<3.14.0"
dependencies = [
    "xarray>=2024",
    "zarr (>=2.14.2,<3.0.0)",
    "dask (>=2023.4.0,<2024)",
    "netcdf4 (>=1.6.3,<2.0.0)",
    "numpy (>=1.25,<2.0.0)",
]

[project.urls]
Repository = "https://github.com/ppr-ocean-ia/dc-tools/tree/main"

[tool.poetry]
version = "0.0.1"


[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pytest-cov = "^4.0.0"
pre-commit = "^3.2.2"
beartype = "^0.13.1"
ruff = "^0.0.263"
black = "^23.3.0"
isort = "^5.12.0"
tox = "^4.24.1"
pydocstyle = "^6.3.0"
copernicusmarine = "^2.0.0"
argopy = "*" # TODO: change to "^1.0.0" when possible

# Even if optional oceanbench still limits argopy
[tool.poetry.group.oceanbench]
optional = true

[tool.poetry.group.oceanbench.dependencies]
oceanbench = {git = "ssh://git@github.com:mercator-ocean/oceanbench.git", branch = "main"}


[build-system]
requires = ["poetry-core", "cmake"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["dctools"]


[tool.ruff]
lint.select = []
lint.ignore = []
lint.ignore-init-module-imports = true

[tool.ruff.lint.isort]
combine-as-imports = true
lines-after-imports = 2
extra-standard-library = ["typing_extensions"]
order-by-type = false
