[project]
name = "dctools"
description = "Basic tools common to all data challenges."
readme = "README.md"
authors = [
    {name="Kamel Ait Mohand"},
    {name="Guillermo Cossio"},
    ]
license = "GPL-3-only"
keywords = ["xarray", "sea-surface-height", "ocean", "benchmark"]
dynamic = [
    "version",
    "classifiers",
    ]
# Too restrictive due to oceanbench
requires-python = ">=3.13.0,<3.14.0"
dependencies = [
    "xarray>=2024",
    "zarr (>=2.14.2,<3.0.0)",
    "dask (>=2023.4.0,<2024)",
    "netcdf4 (>=1.6.3,<2.0.0)",
    "numpy (>=1.25,<2.0.0)",
    "copernicusmarine (>=2.0.0)",
    "argopy>=0.1.14", # TODO: change to "^1.0.0" when possible
    "pyunpack>=0.3",
    "patool>=3.1.3",
    "wget>=3.2",
    "netCDF4>=1.7.2",
    "h5py>=3.13.0"
]

[project.urls]
Repository = "https://github.com/ppr-ocean-ia/dc-tools/tree/main"

[tool.poetry]
version = "0.0.1"


[tool.poetry.group.dev]
optional = false

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pytest-cov = "^6.0.0"
ruff = "^0.9.6"
pydocstyle = "^6.3.0"
mypy = "*"

# Even if optional oceanbench still limits argopy
[tool.poetry.group.oceanbench]
optional = false

[tool.poetry.group.oceanbench.dependencies]
oceanbench = {git = "ssh://git@github.com:mercator-ocean/oceanbench.git", branch = "main"}


[build-system]
requires = ["poetry-core", "cmake"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
disable_error_code = ["import-untyped"]
