channels:
  - conda-forge
  - nodefaults
channel_priority: strict
dependencies:
  - python(">=3.11.0,<3.14.0")
  - poetry
  - esmpy
  - xesmf

  # - python>=3.11,<3.13
  # - netcdf4>=1.6.4,<=1.6.5
  # - pyinterp>=2025.3.0
  # - boost-cpp>=1.79
  # - eigen>=3.3.1
  # - openblas
  # - lapack
  # - blas
  # - cmake
  # - pkg-config